#!/bin/bash
# vim: autoindent tabstop=4 shiftwidth=4 expandtab softtabstop=4 filetype=bash
# -*- mode: sh; indent-tabs-mode: nil; sh-basic-offset: 4 -*-
#
# The following is the minimum amount of code to copy over the client-server-script and no more.
exec 2>&1

# Some container images need this
test -e /etc/profile && . /etc/profile

# "/usr/local/bin" is not always in the $PATH but it needs to be
PATH="/usr/local/bin:$PATH"

function exit_error() {
    local message=$1; shift
    local code=$1; shift
    echo -e "[ERROR]$message\n"
    echo "Exiting"
    if [ -z "$code" ]; then
        exit 1
    else
        exit $code
    fi
}
export -f exit_error

function scp_from_controller() {
    local ssh_id_file=$1; shift
    local src=$1; shift
    local dest=$1; shift
    if [ -z "$ssh_id_file" ]; then
        exit_error "scp_from_controller(): ssh_id_file not defined"
    fi
    if [ -z "$src" ]; then
        exit_error "scp_from_controller(): src not defined"
    fi
    if [ -z "$dest" ]; then
        exit_error "scp_from_controller(): dest not defined"
    fi
    local scp_attempts=1
    local scp_rc=1
    local max_attempts=10
    scp_cmd="scp -o StrictHostKeyChecking=no"
    scp_cmd+=" -o BatchMode=yes"
    scp_cmd+=" -v"
    scp_cmd+=" -o ConnectionAttempts=10"
    scp_cmd+=" -i $ssh_id_file"
    scp_cmd+=" -r $rickshaw_host:$src $dest"
    while [ $scp_rc -gt 0 -a $scp_attempts -lt $max_attempts ]; do
        echo "Trying to scp $rickshaw_host:$src $dest"
        scp_output=`$scp_cmd 2>&1`
        scp_rc=$?
        if [ $scp_rc -gt 0 ]; then
            echo "scp failed, trying again"
            echo "scp exit code: $scp_rc"
            echo "scp command: $scp_cmd"
            echo "scp output:"
            echo "$scp_output"
            sleep $scp_attempts
        fi
        let scp_attempts=$scp_attempts+1
    done
    if [ $scp_attempts -ge $max_attempts ]; then
        exit_error "Could not copy $src from $rickshaw_host"
    fi
}
export -f scp_from_controller

echo "bootstrap env:"
env
echo "bootstrap params:"
echo "$@"
echo
longopts="rickshaw-host:,base-run-dir:,endpoint-run-dir:,cs-label:,roadblock-server:"
longopts+=",roadblock-passwd:,roadblock-id:,disable-tools:,osruntime:,endpoint:"
opts=$(getopt -q -o "" --longoptions "$longopts" -n "getopt.sh" -- "$@");
if [ $? -ne 0 ]; then
    exit_error "\nUnrecognized option specified: $1\n\n"
fi
eval set -- "$opts";
while true; do
    case "$1" in
        --osruntime)
            shift;
            export osruntime="$1"
            shift;
            ;;
        --endpoint)
            shift;
            export endpoint="$1"
            shift;
            ;;
        --rickshaw-host)
            shift;
            export rickshaw_host="$1"
            shift;
            ;;
        --base-run-dir)
            shift;
            export base_run_dir=$1
            shift;
            ;;
        --cs-label)
            shift;
            export cs_label="$1"
            shift;
            ;;
        --endpoint-run-dir)
            shift;
            export endpoint_run_dir="$1"
            shift;
            ;;
        --roadblock-server)
            shift;
            export roadblock_server="$1"
            shift;
            ;;
        --roadblock-passwd)
            shift;
            export roadblock_passwd="$1"
            shift;
            ;;
        --roadblock-id)
            shift;
            export roadblock_id="$1"
            shift;
            ;;
        --disable-tools)
            shift;
            export disable_tools="$1"
            shift;
            ;;
        --)
            shift;
            break;
           ;;
        *)
            exit_error "Unexpected argument [$1]"
            shift;
            break;
            ;;
    esac
done
export ssh_id_file="/tmp/rickshaw_id.rsa"
if [ ! -z "$ssh_id" ]; then
   echo -e "$ssh_id" > $ssh_id_file
   chmod 600 $ssh_id_file
fi
if [ ! -e $ssh_id_file ]; then
    exit_error "ssh key $ssh_id_file was not found"
fi
export config_dir="$base_run_dir/config"
export client_server_config_dir="$config_dir/client-server"
scp_from_controller "$ssh_id_file" "$client_server_config_dir/client-server-script" /usr/local/bin/
if [ -e /usr/local/bin/client-server-script ]; then
    /usr/local/bin/client-server-script
else
    exit_error "Could not find client-server-script"
fi
