#!/usr/local/bin/bash
# -*- mode: sh; indent-tabs-mode: nil; sh-basic-offset: 4 -*-
# vim: autoindent tabstop=4 shiftwidth=4 expandtab softtabstop=4 filetype=bash
#
# The following is the minimum amount of code to start the engine and
# copy over all remaining files that are needed
exec 2>&1

echo "BASH_VERSION=${BASH_VERSION}"

# Some container images need this
test -e /etc/profile && . /etc/profile

# "/usr/local/bin" is not always in the $PATH but it needs to be
PATH="/usr/local/bin:$PATH"

function exit_error() {
    local message=$1; shift
    local code=$1; shift
    echo -e "[ERROR]bootstrap: $message\n"
    echo "Exiting"
    if [ -z "$code" ]; then
        exit 1
    else
        exit $code
    fi
}
export -f exit_error

function scp_from_controller() {
    local ssh_id_file=$1; shift
    local src=$1; shift
    local dest=$1; shift
    local error_handler=$1; shift
    local rb_name=$1; shift
    if [ -z "$ssh_id_file" ]; then
        exit_error "scp_from_controller(): ssh_id_file not defined"
    fi
    if [ -z "$src" ]; then
        exit_error "scp_from_controller(): src not defined"
    fi
    if [ -z "$dest" ]; then
        exit_error "scp_from_controller(): dest not defined"
    fi
    local scp_attempts=1
    local scp_rc=1
    local max_attempts=10
    scp_cmd="scp -o StrictHostKeyChecking=no"
    scp_cmd+=" -o BatchMode=yes"
    scp_cmd+=" -v"
    scp_cmd+=" -o ConnectionAttempts=10"
    scp_cmd+=" -i $ssh_id_file"
    if echo $rickshaw_host | grep -q ":"; then
        scp_cmd+=" -r -6 [$rickshaw_host]:$src $dest"
    else
        scp_cmd+=" -r $rickshaw_host:$src $dest"
    fi
    while [ $scp_rc -gt 0 -a $scp_attempts -lt $max_attempts ]; do
        echo "Trying to scp $rickshaw_host:$src $dest"
        scp_output=`$scp_cmd 2>&1`
        scp_rc=$?
        if [ $scp_rc -gt 0 ]; then
            echo "scp failed, trying again"
            echo "scp exit code: $scp_rc"
            echo "scp command: $scp_cmd"
            echo "scp output:"
            echo "$scp_output"
            sleep $scp_attempts
        fi
        let scp_attempts=$scp_attempts+1
    done
    if [ $scp_attempts -ge $max_attempts ]; then
        case "${error_handler}" in
            "abort")
                if [ -z "{rb_name}" ]; then
                    exit_error "Could not copy ${src} from ${rickshaw_host} with empty roadblock name"
                else
                    abort_error "Could not copy ${src} from ${rickshaw_host}" ${rb_name}
                fi
                ;;
            "exit"|*)
                exit_error "Could not copy ${src} from ${rickshaw_host}"
                ;;
        esac
    fi
}
export -f scp_from_controller

echo "bootstrap env:"
env
echo "bootstrap params:"
echo "$@"
echo
longopts="rickshaw-host:,base-run-dir:,endpoint-run-dir:,cs-label:,roadblock-server:"
longopts+=",roadblock-passwd:,roadblock-id:,disable-tools:,osruntime:,endpoint:,max-sample-failures:"
longopts+=",cpu-partitioning:,max-rb-attempts:,engine-script-start-timeout:"
longopts+=",cpu-partitions:,cpu-partition-index:"
opts=$(getopt -q -o "" --longoptions "$longopts" -n "getopt.sh" -- "$@");
eval set -- "$opts";
while true; do
    case "$1" in
        --cpu-partitions)
            shift;
            export cpu_partitions="${1}"
            shift;
            ;;
        --cpu-partition-index)
            shift;
            export cpu_partition_index="${1}"
            shift;
            ;;
        --cpu-partitioning)
            shift;
            export cpu_partitioning="$1"
            shift;
            ;;
        --osruntime)
            shift;
            export osruntime="$1"
            shift;
            ;;
        --endpoint)
            shift;
            export endpoint="$1"
            shift;
            ;;
        --rickshaw-host)
            shift;
            export rickshaw_host="$1"
            shift;
            ;;
        --base-run-dir)
            shift;
            export base_run_dir=$1
            shift;
            ;;
        --cs-label)
            shift;
            export cs_label="$1"
            shift;
            ;;
        --endpoint-run-dir)
            shift;
            export endpoint_run_dir="$1"
            shift;
            ;;
        --roadblock-server)
            shift;
            export roadblock_server="$1"
            shift;
            ;;
        --roadblock-passwd)
            shift;
            export roadblock_passwd="$1"
            shift;
            ;;
        --roadblock-id)
            shift;
            export roadblock_id="$1"
            shift;
            ;;
        --disable-tools)
            shift;
            export disable_tools="$1"
            shift;
            ;;
        --max-sample-failures)
            shift;
            export max_sample_failures="$1"
            shift;
            ;;
        --max-rb-attempts)
            shift;
            export max_rb_attempts="$1"
            shift;
            ;;
        --engine-script-start-timeout)
            shift;
            export engine_script_start_timeout="$1"
            echo "setting engine_script_start_timeout to $engine_script_start_timeout"
            shift;
            ;;
        --)
            shift;
            break;
           ;;
        *)
            exit_error "Unexpected argument [$1]"
            shift;
            break;
            ;;
    esac
done

if [ -z "$max_rb_attempts" ]; then
    max_rb_attempts=1
    echo "[WARNING] --max-rb-attempts was not used, so setting to default of $max_rb_attempts"
fi

if [ -z "$max_sample_failures" ]; then
    max_sample_failures=3
    echo "[WARNING] --max-sample-failures was not used, so setting to default of $max_sample_failures"
fi

export ssh_id_file="/tmp/rickshaw_id.rsa"
if [ ! -z "$ssh_id" ]; then
    echo "Creating ${ssh_id_file} from \$ssh_id environment variable"
    echo -e "$ssh_id" > $ssh_id_file
    cat $ssh_id_file
    chmod 600 $ssh_id_file
    echo
fi
if [ ! -e $ssh_id_file ]; then
    exit_error "ssh key $ssh_id_file was not found"
fi
export config_dir="$base_run_dir/config"
export engine_config_dir="$config_dir/engine"

if [ -z "${TOOLBOX_HOME}" ]; then
    export TOOLBOX_HOME="/opt/toolbox"
fi

echo "cpu-partitioning:"
if [ "${cpu_partitioning}" == "1" ]; then
    echo "Enabled"

    environment="process"
    if [ "${endpoint}" == "k8s" ]; then
	environment="container"
    fi

    discover_cmd="/usr/local/bin/discover-cpu-partitioning.py --environment=${environment}"
    echo "Determining CPU isolation setup by running: ${discover_cmd}"
    cpu_data=$(${discover_cmd})

    # log the data returned
    echo -e "${cpu_data}"

    isolated_cpus=$(echo -e "${cpu_data}" | grep isolated | awk '{ print $3 }')

    isolated_cpu_args=""
    for cpu in $(echo "${isolated_cpus}" | sed -e "s/,/ /g"); do
        isolated_cpu_args+=" --cpu ${cpu}"
    done
    if [ -z "${cpu_partitions}" ]; then
        cpu_partitions=1
    fi
    if [ -z "${cpu_partition_index}" ]; then
        cpu_partition_index=1
    fi
    partition_cmd="/usr/local/bin/partition-cpus.py --partitions ${cpu_partitions} --partition-index ${cpu_partition_index} ${isolated_cpu_args}"
    echo "Finding the CPU partition by running: ${partition_cmd}"
    partition_cpu_data=$(${partition_cmd})

    # log the data returned
    echo -e "${partition_cpu_data}"

    housekeeping_cpus=$(echo -e "${cpu_data}" | grep housekeeping | awk '{ print $3 }')
    export HK_CPUS=${housekeeping_cpus}
    echo "HK_CPUS=${HK_CPUS}"

    partition_cpus=$(echo -e "${partition_cpu_data}" | grep partition | awk '{ print $3 }')
    export WORKLOAD_CPUS=${partition_cpus}
    echo "WORKLOAD_CPUS=${WORKLOAD_CPUS}"

    # pin myself to the housekeeping cpus so that I and my children
    # are contained there
    taskset --cpu-list --pid ${HK_CPUS} $$
else
    echo "Disabled"
fi
echo

export json_settings_file="/tmp/rickshaw-settings.json.xz"

scp_from_controller "$ssh_id_file" "$config_dir/rickshaw-settings.json.xz" /tmp
if [ ! -e ${json_settings_file} ]; then
    exit_error "Could not find rickshaw-settings.json.xz"
fi

scp_from_controller "$ssh_id_file" "$engine_config_dir/engine-script" /usr/local/bin/
scp_from_controller "$ssh_id_file" "$engine_config_dir/engine-script-library" /usr/local/bin/
scp_from_controller "$ssh_id_file" "$engine_config_dir/roadblock.py" /usr/local/bin
if [ -e /usr/local/bin/engine-script -a -e /usr/local/bin/engine-script-library ]; then
    echo "Execing engine-script:"
    exec /usr/local/bin/engine-script
else
    exit_error "Could not find engine-script or engine-script-library"
fi
