#!/usr/local/bin/bash
# -*- mode: sh; indent-tabs-mode: nil; sh-basic-offset: 4 -*-
# vim: autoindent tabstop=4 shiftwidth=4 expandtab softtabstop=4 filetype=bash
exec 2>&1

echo "BASH_VERSION=${BASH_VERSION}"

test -e /etc/profile && . /etc/profile

if [ ! -e /usr/local/bin/client-server-script-library ]; then
    echo "ERROR: Could not location client-server-script-library"
else
    source client-server-script-library
fi

# Depending on how client-server-script is started, "/usr/local/bin" is not
# always in the $PATH
PATH="/usr/local/bin:$PATH"

echo "client-server-script env:"
env
echo "client-server-script params:"
echo "$@"
echo
echo os-release:
cat /etc/os-release
echo
echo "uname:"
uname -a
echo
version=20200509
echo "version: $version"
echo

leader=controller
load_json_setting "roadblock.timeouts.default" default_timeout
process_opts
validate_core_env
setup_core_env # roadblocks may be used after this

if ! pushd $cs_dir; then
    abort_error "Could not chdir to $cs_dir" engine-init-begin $leader
    exit 1
else
    do_roadblock engine-init-begin $leader $client_server_script_start_timeout
    roadblock_rc=$?
    roadblock_exit_on_error ${roadblock_rc}
fi
do_roadblock engine-init-end $leader $client_server_script_start_timeout
roadblock_rc=$?
roadblock_exit_on_error ${roadblock_rc}


do_roadblock get-data-begin $leader $default_timeout
roadblock_rc=$?
roadblock_exit_on_error ${roadblock_rc}

get_data

do_roadblock get-data-end $leader $default_timeout
roadblock_rc=$?
roadblock_exit_on_error ${roadblock_rc}


do_roadblock collect-sysinfo-begin $leader $default_timeout
roadblock_rc=$?
roadblock_exit_on_error ${roadblock_rc}

collect_sysinfo

do_roadblock collect-sysinfo-end $leader $default_timeout
roadblock_rc=$?
roadblock_exit_on_error ${roadblock_rc}


do_roadblock start-tools-begin $leader $default_timeout
roadblock_rc=$?
roadblock_exit_on_error ${roadblock_rc}

start_tools

do_roadblock start-tools-end $leader $default_timeout
roadblock_rc=$?
roadblock_exit_on_error ${roadblock_rc}


process_bench_roadblocks


do_roadblock stop-tools-begin $leader $default_timeout
stop_tools
do_roadblock stop-tools-end $leader $default_timeout


do_roadblock send-data-begin $leader $default_timeout
send_data
do_roadblock send-data-end $leader $default_timeout


echo -e "\nAll client/server scripts are finished"
/bin/rm -rf $cs_dir
