#!/usr/local/bin/bash
# -*- mode: sh; indent-tabs-mode: nil; sh-basic-offset: 4 -*-
# vim: autoindent tabstop=4 shiftwidth=4 expandtab softtabstop=4 filetype=bash
exec 2>&1

echo "BASH_VERSION=${BASH_VERSION}"

test -e /etc/profile && . /etc/profile

if [ ! -e /usr/local/bin/engine-script-library ]; then
    echo "ERROR: Could not location engine-library"
else
    echo "source engine-script-library: BEGIN"
    source engine-script-library
    echo "source engine-script-library: END"
fi

# Depending on how engine-script is started, "/usr/local/bin" is not
# always in the $PATH
PATH="/usr/local/bin:$PATH"

echo "engine-script env:"
env
echo "engine-script params:"
echo "$@"
echo
echo os-release:
cat /etc/os-release
echo
echo "uname:"
uname -a
echo
version=20200509
echo "version: $version"
echo

leader=controller
load_json_setting "roadblock.timeouts.default" default_timeout
process_opts
validate_core_env
setup_core_env # roadblocks may be used after this

if ! pushd $cs_dir; then
    abort_error "Could not chdir to $cs_dir" engine-init-begin
    exit 1
fi

do_roadblock engine-init-begin ${engine_script_start_timeout}
roadblock_rc=$?
roadblock_exit_on_error ${roadblock_rc}

do_roadblock engine-init-end ${engine_script_start_timeout}
roadblock_rc=$?
roadblock_exit_on_error ${roadblock_rc}


do_roadblock get-data-begin ${default_timeout}
roadblock_rc=$?
roadblock_exit_on_error ${roadblock_rc}

get_data

do_roadblock get-data-end ${default_timeout}
roadblock_rc=$?
roadblock_exit_on_error ${roadblock_rc}


do_roadblock collect-sysinfo-begin ${default_timeout}
roadblock_rc=$?
roadblock_exit_on_error ${roadblock_rc}

collect_sysinfo

do_roadblock collect-sysinfo-end ${default_timeout}
roadblock_rc=$?
roadblock_exit_on_error ${roadblock_rc}


do_roadblock start-tools-begin ${default_timeout}
roadblock_rc=$?
roadblock_exit_on_error ${roadblock_rc}

start_tools

do_roadblock start-tools-end ${default_timeout}
roadblock_rc=$?
roadblock_exit_on_error ${roadblock_rc}


process_bench_roadblocks


do_roadblock stop-tools-begin ${default_timeout}
stop_tools
do_roadblock stop-tools-end ${default_timeout}


do_roadblock send-data-begin ${default_timeout}
do_roadblock send-data-end ${default_timeout} wait-for "/usr/local/bin/engine-script-library send_data '${ssh_id_file}' '${cs_dir}' '${rickshaw_host}' '${archives_dir}/${cs_label}-data.tgz'"


echo -e "\nAll client/server scripts are finished"
/bin/rm -rf $cs_dir
