#!/usr/bin/env bash
# -*- mode: sh; indent-tabs-mode: nil; sh-basic-offset: 4 -*-
# vim: autoindent tabstop=4 shiftwidth=4 expandtab softtabstop=4 filetype=bash

# This script implements the 'osp' endpoint for rickshaw.  It runs 1 or more
# clients and servers as instances/VMs in an Openstack cluster.
#
# Usage:
# osp [--validate] --endpoint-opts=host=<host>,user=<user>,client:n-m,o-p,server:n-m,o-p 
#                    --run-id <id> --base-run-dir --image <location>
#                    --roadblock-server <host> --roadblock-id <id> --roadblock-passwd=<passwd>
#
# If --validate is used all options after client/server will be ignored
#

# Source the base file for common functions and config
this_endpoint_dir=$(dirname `readlink -e $0` | sed -e 'sX/binXX')
endpoint_base_dir=$(cd $this_endpoint_dir >/dev/null && cd .. && /bin/pwd)
if [ -e "$endpoint_base_dir/base" ]; then
    . "$endpoint_base_dir/base"
else
    echo "Could not find endpoint source file "$endpoint_base_dir/base", exiting"
    exit 1
fi

echo "#running osp endpoint"
clear_all_servers="1"
chroot_rbind_mounts="proc dev sys lib/modules usr/src boot var/run"
image_cache_size=3
default_flavor="nfv-large"
default_availability_zone="nova"
osruntime="podman"
host_mounts=""
endpoint_name="osp"
instance_prefix="rickshaw"
base_osruntime_bootstrap="$endpoint_base_dir/osruntime-bootstrap"
project_name="crucible-rickshaw"
new_osp_followers="" # engines which only run tools for openstack nodes
declare -A cpuPartitioning
declare -A flavor
declare -A availability_zone
declare -A ips
declare -A active_compute_nodes
echo "#phaseA"

function cleanup_json() {
    local json="$1"; shift

    echo "cleanup_json: processing ${json}"
    mv ${json} ${json}.tmp
    if jq . ${json}.tmp > ${json}; then
        rm ${json}.tmp
    else
        abort_error "cleanup_json failed to process ${json}" endpoint-deploy-begin
    fi
}

function endpoint_osp_test_stop() {
    local msgs_dir="$1"; shift
    local test_id="$1"; shift
    echo "Running endpoint_osp_test_stop"

    # Delete network related openstack items here (router, floating ip, firewall?)
}

function endpoint_osp_test_start() {
    # This function runs right after a server starts any service and right before a client starts
    # and tries to contect the server's service.  The purpose of this function is to do any
    # work which ensures the client can contact the server.  In some cases there may be nothing
    # to do.  Regardless of the work, the endpoint needs to relay what IP & ports the client
    # needs to use in order to reach the server.  In some cases that may be the information the
    # server has provided to the endpoint, or this information has changed because the endpoint
    # created some sort of proxy to reach the server.

    local msgs_dir="$1"; shift
    local test_id="$1"; shift
    local tx_msgs_dir="$1"; shift
    echo "Running endpoint_osp_test_start"
    # Creating any service or ingress only works if any servers provided information about its
    # IP and ports.
    local this_msg_file="${msgs_dir}/${test_id}:server-start-end.json"
    if [ -e $this_msg_file ]; then
        echo "Found $this_msg_file"
        # Extract the cs-label (server-n, client-y) the IP, and the ports this benchmark is using:
        # server-1 1.2.3.4 30002 30003
        cat $this_msg_file | jq -r '.received[] | if .payload.message.command == "user-object" and .payload.message."user-object".svc.ports then [ .payload.sender.id, .payload.message."user-object".svc.ip, .payload.message."user-object".svc.ports ] | flatten | tostring   else null end' | grep -v null | sed -e 's/"//g' -e 's/\[//' -e 's/\]//' -e 's/,/ /g' >"$endpoint_run_dir/ports.txt"

        while read -u 9 line; do
            echo "line: $line"
            # TODO: set up OSP network services here, like firewall, router, etc
        done 9< "$endpoint_run_dir/ports.txt"
    else
        echo "Did not find $this_msg_file"
    fi
}
echo "#phaseB"

function osp_req_check() {
    if [ -z "$host" ]; then
        exit_error "osp host is not defined"
    fi
    verify_ssh_login $user $host
    # TODO: source overcloudrc or equivalent init file to do osp stuff.  Error out if not found
    osp_cmd=". ./overcloudrc && openstack server list"
    do_ssh ${user}@${host} "$osp_cmd 2>&1" 2>&1 >msg
    rc=$?
    if [ $rc -gt 0 ]; then
        exit_error "Could not run 'openstack' on overcloud host: $osp_cmd"
    fi
    # Validation returns what clients and servers would be used and the userenv
    if [ "$do_validate" == 1 ]; then
        echo_clients_servers
        echo "userenv $userenv"
        exit
    fi
}

function get_opt_field() {
    local input=${1}
    local field=${2}

    case "${field}" in
        "key")
            field="1"
            ;;
        "value")
            field="2-" # return all fields from 2 on, allowing for the delimiter to be a part of the value
            ;;
    esac

    echo "${input}" | cut -d ':' -f ${field}
}

function process_osp_opts() {
    local endpoint_opts="$1"
    for opt in `echo $endpoint_opts | sed -e 's/,/ /g'`; do
        arg=`echo $opt| awk -F: '{print $1}'`
        # The $val may have : in it, so don't use awk to get only the second field
        val=`echo $opt | sed -e s/^$arg://`
        case "$arg" in
            ospconfig)
                ospconfig=$val
                ;;
            client|server|clients|servers)
                addto_clients_servers "$arg" "$val"
                ;;
            host)
                host=$val
                if [ -z "$controller_ipaddr" ]; then
                    controller_ipaddr=`get_controller_ip $host`
                fi
                ;;
            controller-ip)
                controller_ipaddr=$val
                ;;
            user)
                user=$val
                ;;
            userenv)
                userenv=$val
                ;;
            controllers-tool-collect)
                controllers_tool_collect=$val
                ;;
            computes-tool-collect)
                computes_tool_collect=$val
                ;;
            cpu-partitioning)
                # cpu-partitioning is per engine:
                # option format::  cpu-partitioning:<engine-label>:<value>
                # <engine-label> can be 'default' to apply to any engine that is not explicitly specified
                #TODO: validate correct format of <engine-label>
                name=$(get_opt_field "${val}" "key")
                value=$(get_opt_field "${val}" "value")
                if [ ! -z "$name" -a ! -z "$value" ]; then
                    cpuPartitioning[$name]=$value
                else
                    exit_error "Could not properly decode cpu-partitioning for '$val'"
                fi
                ;;
            osruntime)
                osruntime=$val
                ;;
            flavor)
                flavor="$val"
                # flavor is per engine:
                # option format::  flavor:<engine-label>:<flavor>
                # <engine-label> can be 'default' to apply to any engine that is not explicitly specified
                this_key=$(get_opt_field "${val}" "key")
                this_val=$(get_opt_field "${val}" "value")
                flavor[$this_key]=$this_val
                ;;
            availability-zone)
                # node (compute node hostname) is per engine:
                # option format::  node:<engine-label>:<node>
                # <engine-label> can be 'default' to apply to any engine that is not explicitly specified
                this_key=$(get_opt_field "${val}" "key")
                this_value=$(get_opt_field "${val}" "value")
                availability_zone[$this_key]=$this_value
                ;;
            *)
                if echo $arg | grep -q -- "="; then
                    echo "You can't use a \"=\" for assignment in endpoint options"
                    echo "You must use \":\", like `echo $arg | sed -e 's/=/:/'`"
                fi
                exit_error "osp endpoint option [$arg] not supported"
                ;;
        esac
    done

    if [ "${unique_project}" == "1" ]; then
        project_name+="--${run_id}-${endpoint_label}"
    fi
}
echo "#phaseC"

function create_remotehost_engines() {
    echo "create_remotehost_engines()"
}

function create_servers() {
    typeset -n ref1=$1; shift # caller-provided variable name (call-by-reference)
    ref1=""
    local type="$1"; shift
    local instances=""

    ssh_id=$(sed -z 's/\n/\\n/g' ${config_dir}/rickshaw_id.rsa)

    # One openstack server (VM, instance, etc) is created per client and server benchmark engine
    # Servers are not created for collecting tools on compute, controller, network nodes.
    # An osruntime (chroot or podman container) will be created on each of those nodes via launch_osrumtime()

    echo "vm_ssh_key_name: [$vm_ssh_key_name]"
    echo "vm_ssh_key_file: [$vm_ssh_key_file]"
    do_ssh ${user}@${host} "mkdir -p $vm_ssh_key_dir"
    echo "checking for existence of ssh key"
    do_ssh ${user}@${host} "$osp_pre_cmd openstack keypair list --quote minimal -f csv | grep -v Name,Fingerprint" >${endpoint_run_dir}/openstack-keys.txt
    existing_key=`cat ${endpoint_run_dir}/openstack-keys.txt | awk -F, '{print $1}' | grep -v \"Name\" | grep $vm_ssh_key_name` 
    if [ "[$existing_key]" == "[$vm_ssh_key_name]" ]; then
        echo "deleting existing ssh key [$vm_ssh_key_name]"
        do_ssh ${user}@${host} "$osp_pre_cmd openstack keypair delete $vm_ssh_key_name" 
        echo "remaining keypairs"
        do_ssh ${user}@${host} "$osp_pre_cmd openstack keypair list --quote minimal -f csv"
    fi
    echo "creating new ssh key:"
    echo "[$osp_pre_cmd openstack keypair create $vm_ssh_key_name >$vm_ssh_key_file && chmod 600 $vm_ssh_key_file]"
    do_ssh ${user}@${host} "$osp_pre_cmd openstack keypair create $vm_ssh_key_name >$vm_ssh_key_file && chmod 600 $vm_ssh_key_file"
    local osp_servers=""

    if [ "$clear_all_servers" == "1" ]; then # Clear all rickshaw servers, even from other run ids
        do_ssh ${user}@${host} "$osp_pre_cmd openstack server list -f value -c Name" >${endpoint_run_dir}/openstack-existing-servers.txt
        existing_servers=`cat ${endpoint_run_dir}/openstack-existing-servers.txt | grep rickshaw`
        if [ ! -z "$existing_servers" ]; then
            echo "deleting existing servers [$existing_servers]"
            do_ssh ${user}@${host} "$osp_pre_cmd openstack server delete $existing_servers" 
        fi
        do_ssh ${user}@${host} "$osp_pre_cmd openstack port list -f value -c Name" >${endpoint_run_dir}/openstack-existing-ports.txt
        existing_ports=`cat ${endpoint_run_dir}/openstack-existing-ports.txt | grep rickshaw`
        if [ ! -z "$existing_ports" ]; then
            echo "deleting existing ports [$existing_ports]"
            do_ssh ${user}@${host} "$osp_pre_cmd openstack port delete $existing_ports" 
        fi
    fi
    while [ $# -gt 0 ]; do
        cs_label=$1; shift
        vm_name="rickshaw-$run_id-$cs_label"
        mgmt_port_name="mgmt-$vm_name"
        this_osruntime_bootstrap="$vm_name-osrumtime-bootstrap"

        this_flavor=$default_flavor
        if [ ! -z "${flavor[$cs_label]}" ]; then
            this_flavor=${flavor[$cs_label]}
        elif [ ! -z "${flavor[default]}" ]; then
            this_flavor=${flavor[default]}
        fi

        this_availability_zone=$default_availability_zone
        if [ ! -z "${availability_zone[$cs_label]}" ]; then
            this_availability_zone=${availability_zone[$cs_label]}
        elif [ ! -z "${availability_zone[default]}" ]; then
            this_availability_zone=${availability_zone[default]}
        fi

        if [ "$clear_all_servers" == "0" ]; then # Clear only servers with same run id
            do_ssh ${user}@${host} "$osp_pre_cmd openstack server list -f value -c Name" >${endpoint_run_dir}/openstack-existing-servers.txt
            existing_servers=`cat ${endpoint_run_dir}/openstack-existing-servers.txt | grep $vm_name`
            if [ ! -z "$existing_servers" ]; then
                echo "deleting existing server [$existing_servers]"
                do_ssh ${user}@${host} "$osp_pre_cmd openstack server delete $existing_servers" 
            fi
            do_ssh ${user}@${host} "$osp_pre_cmd openstack port list -f value -c Name" >${endpoint_run_dir}/openstack-existing-ports.txt
            existing_ports=`cat ${endpoint_run_dir}/openstack-existing-ports.txt | grep $vm_name`
            if [ ! -z "$existing_ports" ]; then
                echo "deleting existing ports [$existing_ports]"
                do_ssh ${user}@${host} "$osp_pre_cmd openstack port delete $existing_ports" 
            fi
        fi

        echo "checking for existing port"
        do_ssh ${user}@${host} "$osp_pre_cmd openstack port list -f csv --quote minimal | grep -v ID,Name,MAC" >${endpoint_run_dir}/openstack-existing-ports.txt
        echo "existing ports:"
        cat ${endpoint_run_dir}/openstack-existing-ports.txt
        echo "existing_port: [$existing_port]"
        existing_port=`cat ${endpoint_run_dir}/openstack-existing-ports.txt | grep -v ID,Name,Mac | grep $mgmt_port_name | awk -F, '{print $2}'`
        if [ "$existing_port" == "$mgmt_port_name" ]; then
            echo "deleting existing port [$mgmt_port_name]"
            do_ssh ${user}@${host} "$osp_pre_cmd openstack port delete $mgmt_port_name" 
        fi
        do_ssh ${user}@${host} "$osp_pre_cmd openstack port create --network management --no-security-group --disable-port-security $mgmt_port_name"

        echo "creating openstack server $vm_name"

        #this_osruntime_bootstrap="osruntime-bootstrap-$this_cs_label"
        pushd $endpoint_run_dir >/dev/null
        make_osruntime_boostrap_script\
            "$this_osruntime_bootstrap"\
            "$run_id"\
            "$controller_ipaddr"\
            "$endpoint_run_dir"\
            "$cs_label"\
            "$base_run_dir"\
            "0"\
            "$endpoint_label"\
            "$osruntime"\
            "$max_sample_failures"\
            "$max_rb_attempts"\
            "$rb_passwd"\
            "$rb_id"\
            "$ssh_id"\
            "$image"\
            "0"
        #do_scp "" $this_osruntime_bootstrap $user@$host "/"
        #do_ssh $user@$host /$this_osruntime_bootstrap
        do_scp "" "$this_osruntime_bootstrap" "${user}@${host}" "~"
        popd >/dev/null


        do_ssh ${user}@${host} "$osp_pre_cmd openstack server create --flavor nfv-large --nic port-id=$mgmt_port_name --image stream9 --availability-zone nova --key-name $vm_ssh_key_name --user-data $this_osruntime_bootstrap --key-name $vm_ssh_key_name $vm_name --wait" >${endpoint_run_dir}/openstack-create-$vm_name.txt
        #do_ssh ${user}@${host} "$osp_pre_cmd openstack server create --flavor nfv-large --nic port-id=$mgmt_port_name --image stream9 --availability-zone nova --key-name $vm_ssh_key_name $vm_name --wait" >${endpoint_run_dir}/openstack-create-$vm_name.txt
        echo "getting openstack port information for $vm_name"
        do_ssh ${user}@${host} "$osp_pre_cmd openstack port show $mgmt_port_name -f json" >${endpoint_run_dir}/openstack-port-$mgmt_port_name.json
        echo "finding server IP"
        this_server_ip=`jq -r .fixed_ips[0].ip_address ${endpoint_run_dir}/openstack-port-$mgmt_port_name.json`
        echo "this_server_ip: [$this_server_ip]"
        do_ssh ${user}@${host} "$osp_pre_cmd ssh-keygen -R $this_server_ip"
        osp_servers+=" $cs_label"
        ips[$cs_label]=$this_server_ip
    done

    # Remember the compute nodes that are hosting VMs, so tool-collection osruntimes can be launched on them later
    this_compute_node=`do_ssh ${user}@${host} $osp_pre_cmd openstack server show $vm_name -f json | jq -r '."OS-EXT-SRV-ATTR:hypervisor_hostname"'`
    count=1
    if [ "[$this_compute_node]" != "[]" ]; then
        active_compute_nodes[$this_compute_node]="1"
    else
        echo "Something went wrong getting compute node for $vm_name, exiting"
    fi

}

echo "#phaseD"
function cleanup_osruntime() {
    local this_cs_label vm_name mgmt_port_name

    for this_cs_label in ${clients[@]} ${servers[@]}; do
        vm_name="rickshaw-$run_id-$this_cs_label"
        mgmt_port_name="mgmt-$vm_name"
        echo "deletintg VM [$vm_name]"
        do_ssh ${user}@${host} "$osp_pre_cmd openstack server delete $vm_name" >${endpoint_run_dir}/openstack-server-delete-$vm_name.txt
        echo "deletintg network port [$mgmt_port_name]"
        do_ssh ${user}@${host} "$osp_pre_cmd openstack port delete $mgmt_port_name" >${endpoint_run_dir}/openstack-port-delete-$mgmt_port_name.txt
    done
    echo "deletintg keypair [$vm_ssh_key_name]"
    do_ssh ${user}@${host} "$osp_pre_cmd openstack keypair delete $vm_ssh_key_name" >${endpoint_run_dir}/openstack-keypair-delete-$vm_ssh_key_name.txt
    echo "deletintg keyfile [$vm_ssh_key_name]"
    do_ssh ${user}@${host} "rm -f $vm_ssh_key_file"
    do_ssh ${user}@${host} "$osp_pre_cmd openstack server list" >${endpoint_run_dir}/openstack-server-remaining.txt
    echo "remaining rickshaw openstack servers:"
    grep rickshaw ${endpoint_run_dir}/openstack-server-remaining.txt
    do_ssh ${user}@${host} "$osp_pre_cmd openstack port list" >${endpoint_run_dir}/openstack-port-remaining.txt
    echo "remaining rickshaw openstack ports:"
    grep rickshaw ${endpoint_run_dir}/openstack-port-remaining.txt
}


function move_osp_logs() {
    echo "moving engine logs"
    local this_cs_label remote_cs_log_file container_name delete_remote_dir
    mkdir -p $engine_logs_dir
    for this_cs_label in ${clients[@]} ${servers[@]} ${collectors[@]}; do
        this_cs_ssh="ssh $ssh_opts -i $vm_ssh_key_file root@${ips[$this_cs_label]}"
        remote_cs_log_file="$remote_logs_dir/$this_cs_label.txt"
        local_cs_log_file="$engine_logs_dir/$this_cs_label.txt"
        echo "this_cs_label: [$this_cs_label]"
        echo "remote_cs_log_file: [$remote_cs_log_file]"
        echo "this_cs_ssh: [$this_cs_ssh]"
        if [ "$osruntime" == "chroot" ]; then
            do_ssh $user@$host $this_cs_ssh cat $remote_cs_log_file >$local_cs_log_file
        elif [ "$osruntime" == "podman" ]; then
            container_name="${endpoint_label}_${run_id}_${this_cs_label}_${osruntime}"
            do_ssh $user@$host $this_cs_ssh podman logs ${container_name} >$local_cs_log_file
        fi
    done
}

function get_osp_config() {
    echo "getting OSP config"
    #TODO: get instances, networks, etc.
}

function endpoint_osp_sysinfo() {
    local remote_base_dir remote_dir local_dir
    remote_base_dir="/var/lib/crucible"
    remote_dir="${remote_base_dir}/${endpoint_label}_${run_id}"
    local_dir="${endpoint_run_dir}/sysinfo"

    mkdir ${local_dir}

    #TODO: get cluster version info, sosreport, etc
}

function endpoint_osp_cleanup() {
    move_osp_logs
    cleanup_osruntime
}

echo "#phase1"
process_opts "$@"
process_osp_opts "$endpoint_opts"
init_common_dirs
load_settings

echo "#phase2"
remote_base_dir="/var/lib/crucible"
remote_dir="${remote_base_dir}/${endpoint_label}_${run_id}"
remote_cfg_dir="${remote_dir}/cfg"
remote_logs_dir="${remote_dir}/logs"
remote_data_dir="${remote_dir}/data/tmp"
vm_ssh_key_dir=".rickshaw"
vm_ssh_key_name="$run_id-ssh-key"
vm_ssh_key_file="$vm_ssh_key_dir/$vm_ssh_key_name.pem"
osp_pre_cmd=". ./overcloudrc && "

echo "#phase3"
osp_req_check
base_req_check
get_osp_config

echo "#phase4"
echo "This endpoint to run these clients: ${clients[@]}"
echo "This endpoint to run these servers: ${servers[@]}"

# All roadblock particpants are not determined until it is known
# where tools are run.  Once this is known, this information needs
# to be sent back to the controller.
new_osp_followers=""
cs_servers=""
create_servers cs_servers cs ${clients[@]} ${servers[@]}
echo "These openstack servers were created: $cs_servers"
all_engines="$cs_servers"
# launch_osruntime
echo "#phase5"
process_roadblocks osp ${new_osp_followers}
